### PR TITLE
Improvements to SQL formatter

### PR DESCRIPTION
**Pull request by betodealmeida**
This PR rewrites the `query` method in the formatter to use a list comprehension. It also fixes a bug where the values of operators were not processed (I've added a unit test capturing the bug).

### CODE REVIEW

**Comment by klahnakoski** [comment]
Looks good!  thank you!

**Comment by betodealmeida** [comment]
@klahnakoski this was closed without merging, is that intentional?

**Comment by klahnakoski** [comment]
oh, sorry, I thought I did merge it.  doing that now.  :/

**Comment by betodealmeida** [comment]
@klahnakoski thank you!

By the way, I'm using moz-sql-parser for this project: https://github.com/betodealmeida/gsheets-db-api. It's working like a charm, thanks for your work! :)

**Comment by klahnakoski** [comment]
Wow! That makes google sheets much more accessible!

**Pull request merged**
