### PR TITLE
fix:support like expression

### PR DESCRIPTION
**Pull request by faryang-sh**
select * from trade where school LIKE '%shool' and name='abc' and id IN ('1','2')
->
{'select': '*', 'from': 'trade', 'where': {'and': [{'like': [{'literal': 'school'}, {'symbol': 'right'}, 'xiao']}, {'eq': ['name', {'literal': 'abc'}]}, {'in': ['tid', [{'literal': '1'}, {'literal': '2'}]]}]}}

### CODE REVIEW

**Comment by klahnakoski** [comment]
sorry, since there has been no response, this is closed

**Comment by Bhanoday55** [comment]
I have made the changes for like queries. But I'm still getting the error. Should I do anything else. Please resolve.

**Comment by klahnakoski** [comment]
This issue is closed.  It has been resolved with https://github.com/mozilla/moz-sql-parser/commit/00f4cd05cfd5f1c5e768f019f9c3d5387190480f 

This PR was "too smart":  It tried to parse the right-hand-side (RHS) pattern, but did an incomplete job. Treating the RHS as a black-box string was all that's required.

@Bhanoday55 I do not know what you are referring to when you say "i'm still getting the error":  Please open another issue with an example of what you are attempting. It is possible the tests I added did not include your use case, and the code needs to be better.

**Comment by klahnakoski** [comment]
I am wrong. This particular example does not parse.

**Comment by klahnakoski** [comment]
fixed with https://github.com/mozilla/moz-sql-parser/commit/ecd82c3519552f8bd9279cfd045abe5392317ba0

**Pull request closed without merging**
