### PR TITLE
More Unit Tests for the Formatter

### PR DESCRIPTION
**Pull request by tolmanam**

### CODE REVIEW

**Comment by klahnakoski** [comment]
It is better if you make you pull request to the `dev` (default) branch:  Master should never be broken, it is OK if `dev` is broken.

**Comment by tolmanam** [comment]
Ah, ok. Do I need to cancel this request and submit a new one or can this one be moved?

**Comment by klahnakoski** [comment]
I rebased this on `dev`.  (see https://github.com/mozilla/moz-sql-parser/commits/dev) I noticed the other formatting work was done on `master`, so I merged that work into `dev` too.

This suite shows a number of formatting problems, which is excellent!  Good work!

**Comment by klahnakoski** [comment]
I added an issue with the multiline strings: https://github.com/mozilla/moz-sql-parser/issues/28

**Comment by klahnakoski** [comment]
Nope your work was rebased onto `dev`.  Nothing left for you to do.

**Pull request closed without merging**
